import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="p-6">
            <body className={inter.className}>
                <nav className="w-full flex justify-center items-center my-6">
                    <ul className="flex gap-5">
                        <li>
                            {" "}
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            {" "}
                            <Link href="/routing">Routing</Link>
                        </li>
                        <li>
                            {" "}
                            <Link href="/error">Error</Link>
                        </li>
                        <li>
                            {" "}
                            <Link href="/clientSide">Client-Side</Link>
                        </li>
                        <li>
                            {" "}
                            <Link href="/fetch">Fetch</Link>
                        </li>
                    </ul>
                </nav>
                <hr />
                {children}
            </body>
        </html>
    );
}
